/**
 * Regenerates the vendored Ondo token universe from the official token list.
 *
 * Downloads the canonical Ondo Global Markets token list and regenerates:
 *   - lib/pools/ondoTokenList.json      (verbatim vendored mirror / fallback)
 *   - lib/pools/ondoEquityAddresses.ts  (generated, client-safe address list)
 *
 * Run:  npm run update:ondo-tokens
 *
 * The runtime pool fetcher (lib/cache/poolFetchers.ts) refreshes the list from
 * the network on its own, so this script only needs to be re-run to keep the
 * committed fallback + the client-side `isTokenizedStock` lookup current.
 */
import { writeFileSync } from 'fs';
import { join } from 'path';
import {
  ONDO_TOKEN_LIST_URL,
  ETHEREUM_CHAIN_ID,
  parseOndoEquityAddresses,
  type OndoTokenList,
} from '../lib/pools/ondoConfig';

const BSC_CHAIN_ID = 56;
const ROOT = join(__dirname, '..');
const JSON_PATH = join(ROOT, 'lib/pools/ondoTokenList.json');
const ADDRESSES_PATH = join(ROOT, 'lib/pools/ondoEquityAddresses.ts');

function formatAddressArray(addresses: string[], listForSymbols: OndoTokenList, chainId: number): string {
  const symbolByAddress = new Map<string, string>();
  for (const token of listForSymbols.tokens) {
    if (token.chainId === chainId) {
      symbolByAddress.set(String(token.address).toLowerCase(), token.symbol);
    }
  }
  return addresses
    .map((address) => {
      const symbol = symbolByAddress.get(address);
      return `  '${address}',${symbol ? ` // ${symbol}` : ''}`;
    })
    .join('\n');
}

async function main(): Promise<void> {
  console.log(`⬇️  Fetching Ondo token list from ${ONDO_TOKEN_LIST_URL} ...`);
  const res = await fetch(ONDO_TOKEN_LIST_URL, {
    headers: { Accept: 'application/json' },
  });
  if (!res.ok) {
    throw new Error(`Failed to fetch Ondo token list: ${res.status} ${res.statusText}`);
  }
  const list = (await res.json()) as OndoTokenList;
  if (!list || !Array.isArray(list.tokens) || list.tokens.length === 0) {
    throw new Error('Invalid token list: missing or empty "tokens" array');
  }
  const versionStr = list.version
    ? `${list.version.major}.${list.version.minor}.${list.version.patch}`
    : 'unknown';
  console.log(`✅ Fetched "${list.name}" v${versionStr} (${list.tokens.length} tokens, timestamp ${list.timestamp})`);

  // 1. Vendored mirror (pretty-printed for readable diffs).
  writeFileSync(JSON_PATH, JSON.stringify(list, null, 2) + '\n');
  console.log(`📝 Wrote ${JSON_PATH}`);

  // 2. Generated address module (equities only, excludes cash/yield tokens).
  const ethAddresses = parseOndoEquityAddresses(list, ETHEREUM_CHAIN_ID);
  const bscAddresses = parseOndoEquityAddresses(list, BSC_CHAIN_ID);
  const allAddresses = Array.from(new Set([...ethAddresses, ...bscAddresses])).sort();
  console.log(`   Ethereum equities: ${ethAddresses.length}, BSC equities: ${bscAddresses.length}, total unique: ${allAddresses.length}`);

  // The pool fetcher only queries Ethereum, so an empty ETH set would silently
  // empty the Public Equities page — fail loudly instead of writing it.
  if (ethAddresses.length === 0) {
    throw new Error(`No Ethereum (chainId ${ETHEREUM_CHAIN_ID}) equities parsed — refusing to write empty address list`);
  }
  if (bscAddresses.length === 0) {
    console.warn(`⚠️  No BNB Chain (chainId ${BSC_CHAIN_ID}) equities parsed.`);
  }

  const generated = `/**
 * AUTO-GENERATED by scripts/update-ondo-token-list.ts — DO NOT EDIT BY HAND.
 *
 * Source: Ondo "Tokenized Stocks List" v${versionStr} (${list.timestamp})
 * https://github.com/ondoprotocol/ondo-global-markets-token-list
 *
 * Ondo tokenized-equity addresses (lowercased), excluding cash/yield tokens.
 * Used for synchronous, client-safe "is this a tokenized stock?" checks and as
 * the offline fallback for the server-side pool fetcher.
 */

/** Ethereum mainnet (chainId 1) Ondo equity token addresses. */
export const ONDO_EQUITY_ADDRESSES_ETH: readonly string[] = [
${formatAddressArray(ethAddresses, list, ETHEREUM_CHAIN_ID)}
];

/** BNB Chain (chainId 56) Ondo equity token addresses. */
export const ONDO_EQUITY_ADDRESSES_BSC: readonly string[] = [
${formatAddressArray(bscAddresses, list, BSC_CHAIN_ID)}
];

/** All Ondo equity addresses across supported chains (for chain-agnostic membership checks). */
export const ONDO_EQUITY_ADDRESSES: readonly string[] = [
  ...ONDO_EQUITY_ADDRESSES_ETH,
  ...ONDO_EQUITY_ADDRESSES_BSC,
];

/** Ondo equity addresses keyed by chain id. */
export const ONDO_EQUITY_ADDRESSES_BY_CHAIN: Record<number, readonly string[]> = {
  1: ONDO_EQUITY_ADDRESSES_ETH,
  56: ONDO_EQUITY_ADDRESSES_BSC,
};
`;
  writeFileSync(ADDRESSES_PATH, generated);
  console.log(`📝 Wrote ${ADDRESSES_PATH}`);
  console.log('✅ Done.');
}

main().catch((err) => {
  console.error('❌ update-ondo-token-list failed:', err);
  process.exit(1);
});
